#!/usr/bin/env bash

# Configure the site.
wp core install --admin_user=admin --admin_password=password --admin_email="admin@example.com" --title=VCC --url="http://localhost:8080"

# Activate the VCC theme.
wp theme activate vcc

# Nuke the sample posts.
wp post delete 1 2; true

# Nuke the menu.
wp menu delete home-menu; true

# Install plugins.
for plugin in custom-post-type-permalinks advanced-custom-fields wordpress-importer; do
  wp plugin install "$plugin" --activate
done

# Import the data.
wp import --authors=create exports/advanced-custom-field-export.xml
wp import --authors=create exports/victorianclimbingclub.wordpress.2015-11-01.000.xml
