#!/usr/bin/env bash

# Configure the site.
wp core install --admin_user=admin --admin_password=password --admin_email="admin@example.com" --title=VCC --url="http://192.168.99.100:8080"

# Activate the VCC theme.
wp theme activate vcc

# Nuke the sample posts.
# wp post delete 1 2; true

# Nuke the menu.
# wp menu delete home-menu; true

wp plugin install custom-post-type-permalinks --activate

# Import the data.
wp plugin install wordpress-importer --activate
wp import --authors=create exports/vcc.wordpress.2015-08-02.000.xml
